version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      # FLASK_DEBUG no es recomendado para producción. Se muestra aquí solo para desarrollo.
      - FLASK_DEBUG=1 
      - DATABASE_URL=postgresql://examen2_sistemas_user:uAQZagzeNJiSA9GHxx8dvTn1f2E9FSxz@dpg-co6t61mv3ddc73c8ob30-a/examen2_sistemas
    depends_on:
      - db
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    # El comando anterior asume que tu archivo principal se llama app.py y que la instancia de la aplicación Flask se llama 'app' dentro de ese archivo.

  db:
    image: postgres
    environment:
      - POSTGRES_DB=examen2_sistemas
      - POSTGRES_USER=examen2_sistemas_user
      - POSTGRES_PASSWORD=uAQZagzeNJiSA9GHxx8dvTn1f2E9FSxz
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persiste los datos entre reinicios del contenedor

volumes:
  postgres_data:
    # Este volumen se utilizará para persistir los datos de PostgreSQL

# Temporalmente comentado para enfocarnos en app.py
#  extra:
#    build:
#      context: ./extra
#    ports:
#      - "8080:8080"
